apiVersion: v1
kind: Service
metadata:
  name: spotify-frontend-service
spec:
  selector:
    app: spotyify-frontend
  ports:
  - protocol: "TCP"
    port: 3000
    targetPort: 3000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotyify-frontend-deployment
spec:
  selector:
    matchLabels:
      app: spotyify-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: spotyify-frontend
    spec:
      containers:
      - name: spotyify-frontend
        image: updated-frontend
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000